name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: thinca/vim-themis
        path: vim-themis
    - run: printf "%s\n" "PATH=$PATH:$GITHUB_WORKSPACE/vim-themis/bin" >> "$GITHUB_ENV"
    - run: make test
